plugins {
    id 'java'
    id('io.qameta.allure') version '4.0.2'
}

group = 'ru.dev'
version = '1.0-SNAPSHOT'

allure {
    report {//секция репорта
        version.set("2.29.0")
    }
    adapter { //появление папки build\allure-results
        aspectjWeaver.set(true) //обработка аннотации @Step
        frameworks {
            junit5 { //название фреймворка
                adapterVersion.set("2.29.0") //версия интеграция фреймворка и аллюр
            }
        }

    }

}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'com.codeborne:selenide:7.15.0'
    testImplementation 'io.qameta.allure:allure-selenide:2.33.0'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}